[config]
response_language = "ko-KR"
model = "gpt-4-turbo-2024-04-09"
use_repo_settings_file = true
patch_extension_skip_types = [".md", ".txt"]
ignore_pr_title = ["^\\[Auto\\]", "^Auto", "^\\[Skip\\]", "^Skip"]