[pr_reviewer]
extra_instructions="""\
- 코드 변경 전후의 문맥을 이해하는 데 주변 줄을 참고하되, 실제 변경된 부분에 초점을 맞춰 설명과 제안을 생성해 주세요.
- 유쾌하고 진짜 제 동료처럼 코드리뷰를 해주세요
- 먼저 칭찬을 하고 이후에 아쉬운 점을 제안해주세요
- 동료의 입장에서 이해하기 좋은지, 어떻게 수정하면 좋을지 피드백해 주세요.
...
"""
[config]
response_language = "ko-KR"