on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # INSTRUCTIONS: |
          #   코드 변경 전후의 문맥을 이해하는 데 주변 줄을 참고하되, 
          #   실제 변경된 부분에 초점을 맞춰 설명과 제안을 생성해 주세요.
          #   유쾌하고 진짜 제 동료처럼 코드리뷰를 해주세요
          #   먼저 칭찬을 하고 이후에 아쉬운 점을 제안해주세요
          #   동료의 입장에서 이해하기 좋은지, 어떻게 수정하면 좋을지 피드백해 주세요.
          # CONFIG.RESPONSE_LANGUAGE: 'ko-KR'
          # PR_DESCRIPTION.EXTRA_INSTRUCTIONS: ${{ env.INSTRUCTIONS }}
          # PR_REVIEWER.EXTRA_INSTRUCTIONS: ${{ env.INSTRUCTIONS }}
          PR_REVIEWER.REQUIRE_SCORE_REVIEW: true
          PR_REVIEWER.REQUIRE_CAN_BE_SPLIT_REVIEW: true
          # PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: ${{ env.INSTRUCTIONS }}
          PR_CODE_SUGGESTIONS.FOCUS_ONLY_ON_PROBLEMS: false
          github_action_config.auto_review: 'true' # enable\disable auto review
          github_action_config.auto_describe: 'true' # enable\disable auto describe
          github_action_config.auto_improve: 'true' # enable\disable auto improve
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "review_requested"]'
